apiVersion: v1
kind: Service
metadata:
  name: audifarma
  labels:
    app: audifarma
spec:
  selector:
    app: audifarma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
